const Err = require('../common/err');


/**
 * errors generated by Sequelize give too much info to users,
 * so here sanitize them
 */
function sanitizeSequelizeErr(err) {
	if (err.details && err.details.errors) {
		return new Err(err.status, err.details.errors);
	}
	return err;
}


exports.errorHandler = function(err, req, res, next) {
	if (err instanceof Err) {
		res.status(err.status).json(sanitizeSequelizeErr(err));
	} else {
		// programing error, let express to handle that
		next(err);
	}
}
